bof:
  build: ./bof
  volumes:
    - ./bof/home:/home/bof:ro
    - ./bof/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10000:1337"
  expose:
    - "1337"

bof2:
  build: ./bof2
  volumes:
    - ./bof2/home:/home/bof2:ro
    - ./bof2/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10001:1337"
  expose:
    - "1337"

ret2sc:
  build: ./ret2sc
  volumes:
    - ./ret2sc/home:/home/ret2sc:ro
    - ./ret2sc/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10002:1337"
  expose:
    - "1337"

ret2plt:
  build: ./ret2plt
  volumes:
    - ./ret2plt/home:/home/ret2plt:ro
    - ./ret2plt/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10003:1337"
  expose:
    - "1337"

gothijack:
  build: ./gothijack
  volumes:
    - ./gothijack/home:/home/gothijack:ro
    - ./gothijack/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10004:1337"
  expose:
    - "1337"

rop:
  build: ./rop
  volumes:
    - ./rop/home:/home/rop:ro
    - ./rop/xinetd:/etc/xinetd.d/xinetd:ro
  ports:
    - "10005:1337"
  expose:
    - "1337"
